spring.application.name=spring-k8-demo

app.message=${APP_MESSAGE:Hello from Configuration}

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.endpoint.prometheus.access=unrestricted