spring.application.name=spring-k8-demo

# Set APP_MESSAGE in the environment to override this default.
app.message=${APP_MESSAGE:Hello from Configuration}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always