apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spring-k8-demo-chart.fullname" . }}-pvc

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi