spring.application.name=order-service
server.port=8081

app.message=${APP_MESSAGE:Hello from Configuration}

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.endpoint.prometheus.access=unrestricted